openapi: 3.0.1
info:
  title: POTG Summoner v1
  version: v1
paths:
  "/api/potg-lol/summoner/{region}/by-name/{summonerName}":
    get:
      tags:
        - Summoner
      operationId: GetSummoner
      parameters:
        - name: summonerName
          in: path
          required: true
          schema:
            type: string
        - name: region
          in: path
          required: true
          schema:
            type: string
            default: kr
        - name: reFetch
          in: query
          schema:
            type: boolean
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SummonerDto"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FailResponse"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FailResponse"
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FailResponse"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FailResponse"
        "405":
          description: Method Not Allowed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FailResponse"
        "415":
          description: Client Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FailResponse"
        "429":
          description: Too Many Requests
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FailResponse"
        "500":
          description: Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FailResponse"
        "502":
          description: Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FailResponse"
        "503":
          description: Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FailResponse"
        "504":
          description: Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FailResponse"
  "/api/potg-lol/summoner/{region}/{puuid}/matches":
    get:
      tags:
        - Summoner
      operationId: GetMatches
      parameters:
        - name: puuid
          in: path
          required: true
          schema:
            type: string
        - name: region
          in: path
          required: true
          schema:
            type: string
            default: asia
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/MatchEntity"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FailResponse"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FailResponse"
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FailResponse"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FailResponse"
        "405":
          description: Method Not Allowed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FailResponse"
        "415":
          description: Client Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FailResponse"
        "429":
          description: Too Many Requests
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FailResponse"
        "500":
          description: Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FailResponse"
        "502":
          description: Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FailResponse"
        "503":
          description: Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FailResponse"
        "504":
          description: Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FailResponse"
components:
  schemas:
    BadgeEntity:
      type: object
      properties:
        rarity:
          $ref: "#/components/schemas/BadgeRarity"
        name:
          type: string
          nullable: true
        description:
          type: string
          nullable: true
      additionalProperties: false
    BadgeRarity:
      enum:
        - 0
        - 1
        - 2
        - 3
        - 4
      type: integer
      format: int32
    BanEntity:
      type: object
      properties:
        championId:
          type: integer
          format: int32
        championName:
          type: string
          nullable: true
        pickTurn:
          type: integer
          format: int32
      additionalProperties: false
    BannedChampion:
      type: object
      properties:
        championId:
          type: integer
          format: int32
        teamId:
          type: integer
          format: int32
        pickTurn:
          type: integer
          format: int32
      additionalProperties: false
    CurrentGameDto:
      type: object
      properties:
        gameId:
          type: integer
          format: int64
        mapId:
          type: integer
          format: int32
        gameQueueConfigId:
          type: integer
          format: int32
        teams:
          type: array
          items:
            $ref: "#/components/schemas/CurrentGameTeamDto"
          nullable: true
        bannedChampions:
          type: array
          items:
            $ref: "#/components/schemas/BannedChampion"
          nullable: true
        gameStartTime:
          type: integer
          format: int64
      additionalProperties: false
    CurrentGameParticipantDto:
      type: object
      properties:
        teamId:
          type: integer
          format: int32
        summonerId:
          type: string
          nullable: true
        summonerName:
          type: string
          nullable: true
        bot:
          type: boolean
        level:
          type: integer
          format: int32
        spell1Id:
          type: string
          nullable: true
        spell2Id:
          type: string
          nullable: true
        championId:
          type: string
          nullable: true
        perks:
          $ref: "#/components/schemas/Perks"
        ranks:
          type: array
          items:
            $ref: "#/components/schemas/LeagueRankEntity"
          nullable: true
          readOnly: true
      additionalProperties: false
    CurrentGameTeamDto:
      type: object
      properties:
        teamId:
          type: integer
          format: int32
        participants:
          type: array
          items:
            $ref: "#/components/schemas/CurrentGameParticipantDto"
          nullable: true
      additionalProperties: false
    FailResponse:
      type: object
      properties:
        message:
          type: string
          nullable: true
        statusCode:
          type: integer
          format: int32
      additionalProperties: false
    LeagueRankEntity:
      type: object
      properties:
        leagueId:
          type: string
          nullable: true
        queueType:
          type: string
          nullable: true
        tier:
          type: integer
          format: int32
        rank:
          type: integer
          format: int32
        leaguePoints:
          type: integer
          format: int32
        wins:
          type: integer
          format: int32
        losses:
          type: integer
          format: int32
        miniSeries:
          $ref: "#/components/schemas/MiniSeriesEntity"
      additionalProperties: false
    MatchEntity:
      type: object
      properties:
        id:
          type: string
        matchId:
          type: string
          nullable: true
        puuids:
          type: array
          items:
            type: string
          nullable: true
        gameDuration:
          type: integer
          format: int32
        gameEndTimestamp:
          type: integer
          format: int64
        gameId:
          type: integer
          format: int64
        gameMode:
          type: string
          nullable: true
        gameType:
          type: string
          nullable: true
        gameVersion:
          type: string
          nullable: true
        mapId:
          type: integer
          format: int32
        platformId:
          type: string
          nullable: true
        queueId:
          type: integer
          format: int32
        teams:
          type: array
          items:
            $ref: "#/components/schemas/TeamEntity"
          nullable: true
      additionalProperties: false
    MiniSeriesEntity:
      type: object
      properties:
        losses:
          type: integer
          format: int32
        progress:
          type: string
          nullable: true
        target:
          type: integer
          format: int32
        wins:
          type: integer
          format: int32
      additionalProperties: false
    ObjectiveEntity:
      type: object
      properties:
        first:
          type: boolean
        kills:
          type: integer
          format: int32
      additionalProperties: false
    ObjectivesEntity:
      type: object
      properties:
        baron:
          $ref: "#/components/schemas/ObjectiveEntity"
        champion:
          $ref: "#/components/schemas/ObjectiveEntity"
        dragon:
          $ref: "#/components/schemas/ObjectiveEntity"
        inhibitor:
          $ref: "#/components/schemas/ObjectiveEntity"
        riftHerald:
          $ref: "#/components/schemas/ObjectiveEntity"
        tower:
          $ref: "#/components/schemas/ObjectiveEntity"
      additionalProperties: false
    ParticipantEntity:
      type: object
      properties:
        assists:
          type: integer
          format: int64
        baronKills:
          type: integer
          format: int64
        champLevel:
          type: integer
          format: int64
        championId:
          type: integer
          format: int32
        championName:
          type: string
          nullable: true
        damageDealtToBuildings:
          type: integer
          format: int64
        damageDealtToObjectives:
          type: integer
          format: int64
        damageDealtToTurrets:
          type: integer
          format: int64
        damageSelfMitigated:
          type: integer
          format: int64
        deaths:
          type: integer
          format: int64
        detectorWardsPlaced:
          type: integer
          format: int64
        doubleKills:
          type: integer
          format: int64
        dragonKills:
          type: integer
          format: int64
        firstBloodKill:
          type: boolean
        firstTowerKill:
          type: boolean
        goldEarned:
          type: integer
          format: int64
        individualPosition:
          type: string
          nullable: true
        inhibitorKills:
          type: integer
          format: int64
        item0:
          type: integer
          format: int64
        item1:
          type: integer
          format: int64
        item2:
          type: integer
          format: int64
        item3:
          type: integer
          format: int64
        item4:
          type: integer
          format: int64
        item5:
          type: integer
          format: int64
        item6:
          type: integer
          format: int64
        killingSprees:
          type: integer
          format: int64
        kills:
          type: integer
          format: int64
        lane:
          type: string
          nullable: true
        largestKillingSpree:
          type: integer
          format: int64
        largestMultiKill:
          type: integer
          format: int64
        longestTimeSpentLiving:
          type: integer
          format: int64
        magicDamageDealt:
          type: integer
          format: int64
        magicDamageDealtToChampions:
          type: integer
          format: int64
        magicDamageTaken:
          type: integer
          format: int64
        neutralMinionsKilled:
          type: integer
          format: int64
        nexusKills:
          type: integer
          format: int64
        objectivesStolen:
          type: integer
          format: int64
        participantId:
          type: integer
          format: int64
        pentaKills:
          type: integer
          format: int64
        perks:
          $ref: "#/components/schemas/PerksEntity"
        physicalDamageDealt:
          type: integer
          format: int64
        physicalDamageDealtToChampions:
          type: integer
          format: int64
        physicalDamageTaken:
          type: integer
          format: int64
        puuid:
          type: string
          nullable: true
        quadraKills:
          type: integer
          format: int64
        role:
          type: string
          nullable: true
        sightWardsBoughtInGame:
          type: integer
          format: int64
        summoner1Id:
          type: string
          nullable: true
        summoner2Id:
          type: string
          nullable: true
        summonerLevel:
          type: integer
          format: int64
        summonerName:
          type: string
          nullable: true
        teamId:
          type: integer
          format: int64
        totalDamageDealt:
          type: integer
          format: int64
        totalDamageDealtToChampions:
          type: integer
          format: int64
        totalDamageShieldedOnTeammates:
          type: integer
          format: int64
        totalDamageTaken:
          type: integer
          format: int64
        totalHeal:
          type: integer
          format: int64
        totalHealsOnTeammates:
          type: integer
          format: int64
        totalMinionsKilled:
          type: integer
          format: int64
        totalUnitsHealed:
          type: integer
          format: int64
        tripleKills:
          type: integer
          format: int64
        trueDamageDealt:
          type: integer
          format: int64
        trueDamageDealtToChampions:
          type: integer
          format: int64
        trueDamageTaken:
          type: integer
          format: int64
        turretKills:
          type: integer
          format: int64
        visionScore:
          type: integer
          format: int64
        visionWardsBoughtInGame:
          type: integer
          format: int64
        wardsKilled:
          type: integer
          format: int64
        wardsPlaced:
          type: integer
          format: int64
        badges:
          type: array
          items:
            $ref: "#/components/schemas/BadgeEntity"
          nullable: true
      additionalProperties: false
    PerkStatsEntity:
      type: object
      properties:
        defense:
          type: integer
          format: int64
        flex:
          type: integer
          format: int64
        offense:
          type: integer
          format: int64
      additionalProperties: false
    PerkStyleEntity:
      type: object
      properties:
        description:
          type: string
          nullable: true
        selections:
          type: array
          items:
            $ref: "#/components/schemas/PerkStyleSelectionEntity"
          nullable: true
        styleStyle:
          type: integer
          format: int64
      additionalProperties: false
    PerkStyleSelectionEntity:
      type: object
      properties:
        perk:
          type: integer
          format: int64
        var1:
          type: integer
          format: int64
        var2:
          type: integer
          format: int64
        var3:
          type: integer
          format: int64
      additionalProperties: false
    Perks:
      type: object
      properties:
        perkIds:
          type: array
          items:
            type: integer
            format: int32
          nullable: true
        perkStyle:
          type: integer
          format: int32
        perkSubStyle:
          type: integer
          format: int32
      additionalProperties: false
    PerksEntity:
      type: object
      properties:
        statPerks:
          $ref: "#/components/schemas/PerkStatsEntity"
        styles:
          type: array
          items:
            $ref: "#/components/schemas/PerkStyleEntity"
          nullable: true
      additionalProperties: false
    SummonerDto:
      type: object
      properties:
        region:
          type: string
          nullable: true
        subRegion:
          type: string
          nullable: true
        encryptedSummonerId:
          type: string
          nullable: true
        accountId:
          type: string
          nullable: true
        puuid:
          type: string
          nullable: true
        level:
          type: integer
          format: int32
        name:
          type: string
          nullable: true
        searchName:
          type: string
          nullable: true
        profileIconId:
          type: integer
          format: int32
        lastUpdate:
          type: string
          format: date-time
        lastUpdateEpoch:
          type: integer
          format: int64
        ranks:
          type: array
          items:
            $ref: "#/components/schemas/LeagueRankEntity"
          nullable: true
        currentGame:
          $ref: "#/components/schemas/CurrentGameDto"
      additionalProperties: false
    TeamEntity:
      type: object
      properties:
        teamId:
          type: integer
          format: int32
        bans:
          type: array
          items:
            $ref: "#/components/schemas/BanEntity"
          nullable: true
        objectives:
          $ref: "#/components/schemas/ObjectivesEntity"
        win:
          type: boolean
        participants:
          type: array
          items:
            $ref: "#/components/schemas/ParticipantEntity"
          nullable: true
      additionalProperties: false
