/* tslint:disable */
/* eslint-disable */
/**
 * POTG
 * POTG RestAPI Document
 *
 * The version of the OpenAPI document: BETA1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  SummonerDto,
} from '../models/index';
import {
    SummonerDtoFromJSON,
    SummonerDtoToJSON,
} from '../models/index';

export interface GetAutocompleteByRiotIdRequest {
    gameName: string;
    tagLine?: string;
}

/**
 * 
 */
export class AutocompleteApi extends runtime.BaseAPI {

    /**
     * 
     */
    async getAutocompleteByRiotIdRaw(requestParameters: GetAutocompleteByRiotIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SummonerDto>>> {
        if (requestParameters.gameName === null || requestParameters.gameName === undefined) {
            throw new runtime.RequiredError('gameName','Required parameter requestParameters.gameName was null or undefined when calling getAutocompleteByRiotId.');
        }

        const queryParameters: any = {};

        if (requestParameters.tagLine !== undefined) {
            queryParameters['tagLine'] = requestParameters.tagLine;
        }

        if (requestParameters.gameName !== undefined) {
            queryParameters['gameName'] = requestParameters.gameName;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/autocomplete/potg/common/autocomplete/by-riot-id`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SummonerDtoFromJSON));
    }

    /**
     * 
     */
    async getAutocompleteByRiotId(requestParameters: GetAutocompleteByRiotIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SummonerDto>> {
        const response = await this.getAutocompleteByRiotIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
