/* tslint:disable */
/* eslint-disable */
/**
 * POTG
 * POTG RestAPI Document
 *
 * The version of the OpenAPI document: BETA1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

export interface RequestByPuuidRequest {
    puuid: string;
    region: RequestByPuuidRegionEnum;
}

export interface RequestByTagLineWithGameNameRequest {
    tagLine: string;
    gameName: string;
    region: RequestByTagLineWithGameNameRegionEnum;
}

/**
 * 
 */
export class RequestApi extends runtime.BaseAPI {

    /**
     * 
     */
    async requestByPuuidRaw(requestParameters: RequestByPuuidRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.puuid === null || requestParameters.puuid === undefined) {
            throw new runtime.RequiredError('puuid','Required parameter requestParameters.puuid was null or undefined when calling requestByPuuid.');
        }

        if (requestParameters.region === null || requestParameters.region === undefined) {
            throw new runtime.RequiredError('region','Required parameter requestParameters.region was null or undefined when calling requestByPuuid.');
        }

        const queryParameters: any = {};

        if (requestParameters.puuid !== undefined) {
            queryParameters['puuid'] = requestParameters.puuid;
        }

        if (requestParameters.region !== undefined) {
            queryParameters['region'] = requestParameters.region;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/potg/lol/request/by-puuid`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * 
     */
    async requestByPuuid(requestParameters: RequestByPuuidRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.requestByPuuidRaw(requestParameters, initOverrides);
    }

    /**
     * 
     */
    async requestByTagLineWithGameNameRaw(requestParameters: RequestByTagLineWithGameNameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.tagLine === null || requestParameters.tagLine === undefined) {
            throw new runtime.RequiredError('tagLine','Required parameter requestParameters.tagLine was null or undefined when calling requestByTagLineWithGameName.');
        }

        if (requestParameters.gameName === null || requestParameters.gameName === undefined) {
            throw new runtime.RequiredError('gameName','Required parameter requestParameters.gameName was null or undefined when calling requestByTagLineWithGameName.');
        }

        if (requestParameters.region === null || requestParameters.region === undefined) {
            throw new runtime.RequiredError('region','Required parameter requestParameters.region was null or undefined when calling requestByTagLineWithGameName.');
        }

        const queryParameters: any = {};

        if (requestParameters.tagLine !== undefined) {
            queryParameters['tagLine'] = requestParameters.tagLine;
        }

        if (requestParameters.gameName !== undefined) {
            queryParameters['gameName'] = requestParameters.gameName;
        }

        if (requestParameters.region !== undefined) {
            queryParameters['region'] = requestParameters.region;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/potg/lol/request/by-riot-id`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * 
     */
    async requestByTagLineWithGameName(requestParameters: RequestByTagLineWithGameNameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.requestByTagLineWithGameNameRaw(requestParameters, initOverrides);
    }

}

/**
 * @export
 */
export const RequestByPuuidRegionEnum = {
    Br1: 'BR1',
    Eun1: 'EUN1',
    Euw1: 'EUW1',
    Jp1: 'JP1',
    Kr: 'KR',
    La1: 'LA1',
    La2: 'LA2',
    Na1: 'NA1',
    Oc1: 'OC1',
    Ph2: 'PH2',
    Ru: 'RU',
    Sg2: 'SG2',
    Th2: 'TH2',
    Tr1: 'TR1',
    Tw2: 'TW2',
    Vn2: 'VN2'
} as const;
export type RequestByPuuidRegionEnum = typeof RequestByPuuidRegionEnum[keyof typeof RequestByPuuidRegionEnum];
/**
 * @export
 */
export const RequestByTagLineWithGameNameRegionEnum = {
    Br1: 'BR1',
    Eun1: 'EUN1',
    Euw1: 'EUW1',
    Jp1: 'JP1',
    Kr: 'KR',
    La1: 'LA1',
    La2: 'LA2',
    Na1: 'NA1',
    Oc1: 'OC1',
    Ph2: 'PH2',
    Ru: 'RU',
    Sg2: 'SG2',
    Th2: 'TH2',
    Tr1: 'TR1',
    Tw2: 'TW2',
    Vn2: 'VN2'
} as const;
export type RequestByTagLineWithGameNameRegionEnum = typeof RequestByTagLineWithGameNameRegionEnum[keyof typeof RequestByTagLineWithGameNameRegionEnum];
