/* tslint:disable */
/* eslint-disable */
/**
 * POTG
 * POTG RestAPI Document
 *
 * The version of the OpenAPI document: BETA1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Summoner,
} from '../models/index';
import {
    SummonerFromJSON,
    SummonerToJSON,
} from '../models/index';

export interface GetSummonerByPuuidRequest {
    puuid: string;
    region: GetSummonerByPuuidRegionEnum;
}

/**
 * 
 */
export class SummonerApi extends runtime.BaseAPI {

    /**
     * 
     */
    async getSummonerByPuuidRaw(requestParameters: GetSummonerByPuuidRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Summoner>> {
        if (requestParameters.puuid === null || requestParameters.puuid === undefined) {
            throw new runtime.RequiredError('puuid','Required parameter requestParameters.puuid was null or undefined when calling getSummonerByPuuid.');
        }

        if (requestParameters.region === null || requestParameters.region === undefined) {
            throw new runtime.RequiredError('region','Required parameter requestParameters.region was null or undefined when calling getSummonerByPuuid.');
        }

        const queryParameters: any = {};

        if (requestParameters.region !== undefined) {
            queryParameters['region'] = requestParameters.region;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/potg/lol/summoner/by-puuid/{puuid}`.replace(`{${"puuid"}}`, encodeURIComponent(String(requestParameters.puuid))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SummonerFromJSON(jsonValue));
    }

    /**
     * 
     */
    async getSummonerByPuuid(requestParameters: GetSummonerByPuuidRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Summoner> {
        const response = await this.getSummonerByPuuidRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GetSummonerByPuuidRegionEnum = {
    Br1: 'BR1',
    Eun1: 'EUN1',
    Euw1: 'EUW1',
    Jp1: 'JP1',
    Kr: 'KR',
    La1: 'LA1',
    La2: 'LA2',
    Na1: 'NA1',
    Oc1: 'OC1',
    Ph2: 'PH2',
    Ru: 'RU',
    Sg2: 'SG2',
    Th2: 'TH2',
    Tr1: 'TR1',
    Tw2: 'TW2',
    Vn2: 'VN2'
} as const;
export type GetSummonerByPuuidRegionEnum = typeof GetSummonerByPuuidRegionEnum[keyof typeof GetSummonerByPuuidRegionEnum];
