/* tslint:disable */
/* eslint-disable */
/**
 * POTG Summoner v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { BadgeRarity } from './badge-rarity';

/**
 * 
 * @export
 * @interface BadgeEntity
 */
export interface BadgeEntity {
    /**
     * 
     * @type {BadgeRarity}
     * @memberof BadgeEntity
     */
    'rarity'?: BadgeRarity;
    /**
     * 
     * @type {string}
     * @memberof BadgeEntity
     */
    'name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BadgeEntity
     */
    'description'?: string | null;
}

