/* tslint:disable */
/* eslint-disable */
/**
 * POTG Summoner v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface BanEntity
 */
export interface BanEntity {
    /**
     * 
     * @type {number}
     * @memberof BanEntity
     */
    'championId'?: number;
    /**
     * 
     * @type {string}
     * @memberof BanEntity
     */
    'championName'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof BanEntity
     */
    'pickTurn'?: number;
}

