/* tslint:disable */
/* eslint-disable */
/**
 * POTG Summoner v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CurrentGameParticipantDto } from './current-game-participant-dto';

/**
 * 
 * @export
 * @interface CurrentGameTeamDto
 */
export interface CurrentGameTeamDto {
    /**
     * 
     * @type {number}
     * @memberof CurrentGameTeamDto
     */
    'teamId'?: number;
    /**
     * 
     * @type {Array<CurrentGameParticipantDto>}
     * @memberof CurrentGameTeamDto
     */
    'participants'?: Array<CurrentGameParticipantDto> | null;
}

