/* tslint:disable */
/* eslint-disable */
/**
 * POTG Summoner v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { LeagueRankEntity } from './league-rank-entity';
import { Perks } from './perks';

/**
 * 
 * @export
 * @interface CurrentGameParticipantDto
 */
export interface CurrentGameParticipantDto {
    /**
     * 
     * @type {number}
     * @memberof CurrentGameParticipantDto
     */
    'teamId'?: number;
    /**
     * 
     * @type {string}
     * @memberof CurrentGameParticipantDto
     */
    'summonerId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CurrentGameParticipantDto
     */
    'summonerName'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof CurrentGameParticipantDto
     */
    'bot'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof CurrentGameParticipantDto
     */
    'level'?: number;
    /**
     * 
     * @type {string}
     * @memberof CurrentGameParticipantDto
     */
    'spell1Id'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CurrentGameParticipantDto
     */
    'spell2Id'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CurrentGameParticipantDto
     */
    'championId'?: string | null;
    /**
     * 
     * @type {Perks}
     * @memberof CurrentGameParticipantDto
     */
    'perks'?: Perks;
    /**
     * 
     * @type {Array<LeagueRankEntity>}
     * @memberof CurrentGameParticipantDto
     */
    'ranks'?: Array<LeagueRankEntity> | null;
}

