/* tslint:disable */
/* eslint-disable */
/**
 * POTG Summoner v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { BannedChampion } from './banned-champion';
import { CurrentGameTeamDto } from './current-game-team-dto';

/**
 * 
 * @export
 * @interface CurrentGameDto
 */
export interface CurrentGameDto {
    /**
     * 
     * @type {number}
     * @memberof CurrentGameDto
     */
    'gameId'?: number;
    /**
     * 
     * @type {number}
     * @memberof CurrentGameDto
     */
    'mapId'?: number;
    /**
     * 
     * @type {number}
     * @memberof CurrentGameDto
     */
    'gameQueueConfigId'?: number;
    /**
     * 
     * @type {Array<CurrentGameTeamDto>}
     * @memberof CurrentGameDto
     */
    'teams'?: Array<CurrentGameTeamDto> | null;
    /**
     * 
     * @type {Array<BannedChampion>}
     * @memberof CurrentGameDto
     */
    'bannedChampions'?: Array<BannedChampion> | null;
    /**
     * 
     * @type {number}
     * @memberof CurrentGameDto
     */
    'gameStartTime'?: number;
}

