/* tslint:disable */
/* eslint-disable */
/**
 * POTG Summoner v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { MiniSeriesEntity } from './mini-series-entity';

/**
 * 
 * @export
 * @interface LeagueRankEntity
 */
export interface LeagueRankEntity {
    /**
     * 
     * @type {string}
     * @memberof LeagueRankEntity
     */
    'leagueId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LeagueRankEntity
     */
    'queueType'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof LeagueRankEntity
     */
    'tier'?: number;
    /**
     * 
     * @type {number}
     * @memberof LeagueRankEntity
     */
    'rank'?: number;
    /**
     * 
     * @type {number}
     * @memberof LeagueRankEntity
     */
    'leaguePoints'?: number;
    /**
     * 
     * @type {number}
     * @memberof LeagueRankEntity
     */
    'wins'?: number;
    /**
     * 
     * @type {number}
     * @memberof LeagueRankEntity
     */
    'losses'?: number;
    /**
     * 
     * @type {MiniSeriesEntity}
     * @memberof LeagueRankEntity
     */
    'miniSeries'?: MiniSeriesEntity;
}

