/* tslint:disable */
/* eslint-disable */
/**
 * POTG Summoner v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { TeamEntity } from './team-entity';

/**
 * 
 * @export
 * @interface MatchEntity
 */
export interface MatchEntity {
    /**
     * 
     * @type {string}
     * @memberof MatchEntity
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof MatchEntity
     */
    'matchId'?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof MatchEntity
     */
    'puuids'?: Array<string> | null;
    /**
     * 
     * @type {number}
     * @memberof MatchEntity
     */
    'gameDuration'?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchEntity
     */
    'gameEndTimestamp'?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchEntity
     */
    'gameId'?: number;
    /**
     * 
     * @type {string}
     * @memberof MatchEntity
     */
    'gameMode'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MatchEntity
     */
    'gameType'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MatchEntity
     */
    'gameVersion'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof MatchEntity
     */
    'mapId'?: number;
    /**
     * 
     * @type {string}
     * @memberof MatchEntity
     */
    'platformId'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof MatchEntity
     */
    'queueId'?: number;
    /**
     * 
     * @type {Array<TeamEntity>}
     * @memberof MatchEntity
     */
    'teams'?: Array<TeamEntity> | null;
}

