/* tslint:disable */
/* eslint-disable */
/**
 * POTG Summoner v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ObjectiveEntity
 */
export interface ObjectiveEntity {
    /**
     * 
     * @type {boolean}
     * @memberof ObjectiveEntity
     */
    'first'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ObjectiveEntity
     */
    'kills'?: number;
}

