/* tslint:disable */
/* eslint-disable */
/**
 * POTG Summoner v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ObjectiveEntity } from './objective-entity';

/**
 * 
 * @export
 * @interface ObjectivesEntity
 */
export interface ObjectivesEntity {
    /**
     * 
     * @type {ObjectiveEntity}
     * @memberof ObjectivesEntity
     */
    'baron'?: ObjectiveEntity;
    /**
     * 
     * @type {ObjectiveEntity}
     * @memberof ObjectivesEntity
     */
    'champion'?: ObjectiveEntity;
    /**
     * 
     * @type {ObjectiveEntity}
     * @memberof ObjectivesEntity
     */
    'dragon'?: ObjectiveEntity;
    /**
     * 
     * @type {ObjectiveEntity}
     * @memberof ObjectivesEntity
     */
    'inhibitor'?: ObjectiveEntity;
    /**
     * 
     * @type {ObjectiveEntity}
     * @memberof ObjectivesEntity
     */
    'riftHerald'?: ObjectiveEntity;
    /**
     * 
     * @type {ObjectiveEntity}
     * @memberof ObjectivesEntity
     */
    'tower'?: ObjectiveEntity;
}

