/* tslint:disable */
/* eslint-disable */
/**
 * POTG Summoner v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { BadgeEntity } from './badge-entity';
import { PerksEntity } from './perks-entity';

/**
 * 
 * @export
 * @interface ParticipantEntity
 */
export interface ParticipantEntity {
    /**
     * 
     * @type {number}
     * @memberof ParticipantEntity
     */
    'assists'?: number;
    /**
     * 
     * @type {number}
     * @memberof ParticipantEntity
     */
    'baronKills'?: number;
    /**
     * 
     * @type {number}
     * @memberof ParticipantEntity
     */
    'champLevel'?: number;
    /**
     * 
     * @type {number}
     * @memberof ParticipantEntity
     */
    'championId'?: number;
    /**
     * 
     * @type {string}
     * @memberof ParticipantEntity
     */
    'championName'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ParticipantEntity
     */
    'damageDealtToBuildings'?: number;
    /**
     * 
     * @type {number}
     * @memberof ParticipantEntity
     */
    'damageDealtToObjectives'?: number;
    /**
     * 
     * @type {number}
     * @memberof ParticipantEntity
     */
    'damageDealtToTurrets'?: number;
    /**
     * 
     * @type {number}
     * @memberof ParticipantEntity
     */
    'damageSelfMitigated'?: number;
    /**
     * 
     * @type {number}
     * @memberof ParticipantEntity
     */
    'deaths'?: number;
    /**
     * 
     * @type {number}
     * @memberof ParticipantEntity
     */
    'detectorWardsPlaced'?: number;
    /**
     * 
     * @type {number}
     * @memberof ParticipantEntity
     */
    'doubleKills'?: number;
    /**
     * 
     * @type {number}
     * @memberof ParticipantEntity
     */
    'dragonKills'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ParticipantEntity
     */
    'firstBloodKill'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ParticipantEntity
     */
    'firstTowerKill'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ParticipantEntity
     */
    'goldEarned'?: number;
    /**
     * 
     * @type {string}
     * @memberof ParticipantEntity
     */
    'individualPosition'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ParticipantEntity
     */
    'inhibitorKills'?: number;
    /**
     * 
     * @type {number}
     * @memberof ParticipantEntity
     */
    'item0'?: number;
    /**
     * 
     * @type {number}
     * @memberof ParticipantEntity
     */
    'item1'?: number;
    /**
     * 
     * @type {number}
     * @memberof ParticipantEntity
     */
    'item2'?: number;
    /**
     * 
     * @type {number}
     * @memberof ParticipantEntity
     */
    'item3'?: number;
    /**
     * 
     * @type {number}
     * @memberof ParticipantEntity
     */
    'item4'?: number;
    /**
     * 
     * @type {number}
     * @memberof ParticipantEntity
     */
    'item5'?: number;
    /**
     * 
     * @type {number}
     * @memberof ParticipantEntity
     */
    'item6'?: number;
    /**
     * 
     * @type {number}
     * @memberof ParticipantEntity
     */
    'killingSprees'?: number;
    /**
     * 
     * @type {number}
     * @memberof ParticipantEntity
     */
    'kills'?: number;
    /**
     * 
     * @type {string}
     * @memberof ParticipantEntity
     */
    'lane'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ParticipantEntity
     */
    'largestKillingSpree'?: number;
    /**
     * 
     * @type {number}
     * @memberof ParticipantEntity
     */
    'largestMultiKill'?: number;
    /**
     * 
     * @type {number}
     * @memberof ParticipantEntity
     */
    'longestTimeSpentLiving'?: number;
    /**
     * 
     * @type {number}
     * @memberof ParticipantEntity
     */
    'magicDamageDealt'?: number;
    /**
     * 
     * @type {number}
     * @memberof ParticipantEntity
     */
    'magicDamageDealtToChampions'?: number;
    /**
     * 
     * @type {number}
     * @memberof ParticipantEntity
     */
    'magicDamageTaken'?: number;
    /**
     * 
     * @type {number}
     * @memberof ParticipantEntity
     */
    'neutralMinionsKilled'?: number;
    /**
     * 
     * @type {number}
     * @memberof ParticipantEntity
     */
    'nexusKills'?: number;
    /**
     * 
     * @type {number}
     * @memberof ParticipantEntity
     */
    'objectivesStolen'?: number;
    /**
     * 
     * @type {number}
     * @memberof ParticipantEntity
     */
    'participantId'?: number;
    /**
     * 
     * @type {number}
     * @memberof ParticipantEntity
     */
    'pentaKills'?: number;
    /**
     * 
     * @type {PerksEntity}
     * @memberof ParticipantEntity
     */
    'perks'?: PerksEntity;
    /**
     * 
     * @type {number}
     * @memberof ParticipantEntity
     */
    'physicalDamageDealt'?: number;
    /**
     * 
     * @type {number}
     * @memberof ParticipantEntity
     */
    'physicalDamageDealtToChampions'?: number;
    /**
     * 
     * @type {number}
     * @memberof ParticipantEntity
     */
    'physicalDamageTaken'?: number;
    /**
     * 
     * @type {string}
     * @memberof ParticipantEntity
     */
    'puuid'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ParticipantEntity
     */
    'quadraKills'?: number;
    /**
     * 
     * @type {string}
     * @memberof ParticipantEntity
     */
    'role'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ParticipantEntity
     */
    'sightWardsBoughtInGame'?: number;
    /**
     * 
     * @type {string}
     * @memberof ParticipantEntity
     */
    'summoner1Id'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ParticipantEntity
     */
    'summoner2Id'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ParticipantEntity
     */
    'summonerLevel'?: number;
    /**
     * 
     * @type {string}
     * @memberof ParticipantEntity
     */
    'summonerName'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ParticipantEntity
     */
    'teamId'?: number;
    /**
     * 
     * @type {number}
     * @memberof ParticipantEntity
     */
    'totalDamageDealt'?: number;
    /**
     * 
     * @type {number}
     * @memberof ParticipantEntity
     */
    'totalDamageDealtToChampions'?: number;
    /**
     * 
     * @type {number}
     * @memberof ParticipantEntity
     */
    'totalDamageShieldedOnTeammates'?: number;
    /**
     * 
     * @type {number}
     * @memberof ParticipantEntity
     */
    'totalDamageTaken'?: number;
    /**
     * 
     * @type {number}
     * @memberof ParticipantEntity
     */
    'totalHeal'?: number;
    /**
     * 
     * @type {number}
     * @memberof ParticipantEntity
     */
    'totalHealsOnTeammates'?: number;
    /**
     * 
     * @type {number}
     * @memberof ParticipantEntity
     */
    'totalMinionsKilled'?: number;
    /**
     * 
     * @type {number}
     * @memberof ParticipantEntity
     */
    'totalUnitsHealed'?: number;
    /**
     * 
     * @type {number}
     * @memberof ParticipantEntity
     */
    'tripleKills'?: number;
    /**
     * 
     * @type {number}
     * @memberof ParticipantEntity
     */
    'trueDamageDealt'?: number;
    /**
     * 
     * @type {number}
     * @memberof ParticipantEntity
     */
    'trueDamageDealtToChampions'?: number;
    /**
     * 
     * @type {number}
     * @memberof ParticipantEntity
     */
    'trueDamageTaken'?: number;
    /**
     * 
     * @type {number}
     * @memberof ParticipantEntity
     */
    'turretKills'?: number;
    /**
     * 
     * @type {number}
     * @memberof ParticipantEntity
     */
    'visionScore'?: number;
    /**
     * 
     * @type {number}
     * @memberof ParticipantEntity
     */
    'visionWardsBoughtInGame'?: number;
    /**
     * 
     * @type {number}
     * @memberof ParticipantEntity
     */
    'wardsKilled'?: number;
    /**
     * 
     * @type {number}
     * @memberof ParticipantEntity
     */
    'wardsPlaced'?: number;
    /**
     * 
     * @type {Array<BadgeEntity>}
     * @memberof ParticipantEntity
     */
    'badges'?: Array<BadgeEntity> | null;
}

