/* tslint:disable */
/* eslint-disable */
/**
 * POTG Summoner v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { PerkStatsEntity } from './perk-stats-entity';
import { PerkStyleEntity } from './perk-style-entity';

/**
 * 
 * @export
 * @interface PerksEntity
 */
export interface PerksEntity {
    /**
     * 
     * @type {PerkStatsEntity}
     * @memberof PerksEntity
     */
    'statPerks'?: PerkStatsEntity;
    /**
     * 
     * @type {Array<PerkStyleEntity>}
     * @memberof PerksEntity
     */
    'styles'?: Array<PerkStyleEntity> | null;
}

