/* tslint:disable */
/* eslint-disable */
/**
 * POTG Summoner v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Perks
 */
export interface Perks {
    /**
     * 
     * @type {Array<number>}
     * @memberof Perks
     */
    'perkIds'?: Array<number> | null;
    /**
     * 
     * @type {number}
     * @memberof Perks
     */
    'perkStyle'?: number;
    /**
     * 
     * @type {number}
     * @memberof Perks
     */
    'perkSubStyle'?: number;
}

