/* tslint:disable */
/* eslint-disable */
/**
 * POTG Summoner v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PerkStyleSelectionEntity } from "./perk-style-selection-entity";

/**
 *
 * @export
 * @interface PerkStyleEntity
 */
export interface PerkStyleEntity {
  /**
   *
   * @type {string}
   * @memberof PerkStyleEntity
   */
  description?: string | null;
  /**
   *
   * @type {Array<PerkStyleSelectionEntity>}
   * @memberof PerkStyleEntity
   */
  selections?: Array<PerkStyleSelectionEntity> | null;
  /**
   *
   * @type {number}
   * @memberof PerkStyleEntity
   */
  styleStyle?: number;
}
