/* tslint:disable */
/* eslint-disable */
/**
 * POTG Summoner v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PerkStatsEntity
 */
export interface PerkStatsEntity {
    /**
     * 
     * @type {number}
     * @memberof PerkStatsEntity
     */
    'defense'?: number;
    /**
     * 
     * @type {number}
     * @memberof PerkStatsEntity
     */
    'flex'?: number;
    /**
     * 
     * @type {number}
     * @memberof PerkStatsEntity
     */
    'offense'?: number;
}

