/* tslint:disable */
/* eslint-disable */
/**
 * POTG
 * POTG RestAPI Document
 *
 * The version of the OpenAPI document: BETA1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AutocompleteDto
 */
export interface AutocompleteDto {
    /**
     * 
     * @type {string}
     * @memberof AutocompleteDto
     */
    puuid: string;
    /**
     * 
     * @type {string}
     * @memberof AutocompleteDto
     */
    gameName: string;
    /**
     * 
     * @type {string}
     * @memberof AutocompleteDto
     */
    tagLine: string;
    /**
     * 
     * @type {number}
     * @memberof AutocompleteDto
     */
    profileIconId: number;
    /**
     * 
     * @type {number}
     * @memberof AutocompleteDto
     */
    summonerLevel: number;
    /**
     * 
     * @type {string}
     * @memberof AutocompleteDto
     */
    tier: string;
    /**
     * 
     * @type {string}
     * @memberof AutocompleteDto
     */
    rank: string;
    /**
     * 
     * @type {number}
     * @memberof AutocompleteDto
     */
    leaguePoint: number;
}

/**
 * Check if a given object implements the AutocompleteDto interface.
 */
export function instanceOfAutocompleteDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "puuid" in value;
    isInstance = isInstance && "gameName" in value;
    isInstance = isInstance && "tagLine" in value;
    isInstance = isInstance && "profileIconId" in value;
    isInstance = isInstance && "summonerLevel" in value;
    isInstance = isInstance && "tier" in value;
    isInstance = isInstance && "rank" in value;
    isInstance = isInstance && "leaguePoint" in value;

    return isInstance;
}

export function AutocompleteDtoFromJSON(json: any): AutocompleteDto {
    return AutocompleteDtoFromJSONTyped(json, false);
}

export function AutocompleteDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AutocompleteDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'puuid': json['puuid'],
        'gameName': json['gameName'],
        'tagLine': json['tagLine'],
        'profileIconId': json['profileIconId'],
        'summonerLevel': json['summonerLevel'],
        'tier': json['tier'],
        'rank': json['rank'],
        'leaguePoint': json['leaguePoint'],
    };
}

export function AutocompleteDtoToJSON(value?: AutocompleteDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'puuid': value.puuid,
        'gameName': value.gameName,
        'tagLine': value.tagLine,
        'profileIconId': value.profileIconId,
        'summonerLevel': value.summonerLevel,
        'tier': value.tier,
        'rank': value.rank,
        'leaguePoint': value.leaguePoint,
    };
}

