/* tslint:disable */
/* eslint-disable */
/**
 * POTG
 * POTG RestAPI Document
 *
 * The version of the OpenAPI document: BETA1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BannedChampion
 */
export interface BannedChampion {
    /**
     * 
     * @type {number}
     * @memberof BannedChampion
     */
    pickTurn: number;
    /**
     * 
     * @type {number}
     * @memberof BannedChampion
     */
    championId: number;
    /**
     * 
     * @type {number}
     * @memberof BannedChampion
     */
    teamId: number;
}

/**
 * Check if a given object implements the BannedChampion interface.
 */
export function instanceOfBannedChampion(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "pickTurn" in value;
    isInstance = isInstance && "championId" in value;
    isInstance = isInstance && "teamId" in value;

    return isInstance;
}

export function BannedChampionFromJSON(json: any): BannedChampion {
    return BannedChampionFromJSONTyped(json, false);
}

export function BannedChampionFromJSONTyped(json: any, ignoreDiscriminator: boolean): BannedChampion {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'pickTurn': json['pickTurn'],
        'championId': json['championId'],
        'teamId': json['teamId'],
    };
}

export function BannedChampionToJSON(value?: BannedChampion | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'pickTurn': value.pickTurn,
        'championId': value.championId,
        'teamId': value.teamId,
    };
}

