/* tslint:disable */
/* eslint-disable */
/**
 * POTG
 * POTG RestAPI Document
 *
 * The version of the OpenAPI document: BETA1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GameCustomizationObject
 */
export interface GameCustomizationObject {
    /**
     * 
     * @type {string}
     * @memberof GameCustomizationObject
     */
    category: string;
    /**
     * 
     * @type {string}
     * @memberof GameCustomizationObject
     */
    content: string;
}

/**
 * Check if a given object implements the GameCustomizationObject interface.
 */
export function instanceOfGameCustomizationObject(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "category" in value;
    isInstance = isInstance && "content" in value;

    return isInstance;
}

export function GameCustomizationObjectFromJSON(json: any): GameCustomizationObject {
    return GameCustomizationObjectFromJSONTyped(json, false);
}

export function GameCustomizationObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameCustomizationObject {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'category': json['category'],
        'content': json['content'],
    };
}

export function GameCustomizationObjectToJSON(value?: GameCustomizationObject | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'category': value.category,
        'content': value.content,
    };
}

