/* tslint:disable */
/* eslint-disable */
/**
 * POTG
 * POTG RestAPI Document
 *
 * The version of the OpenAPI document: BETA1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MiniSeriesDto
 */
export interface MiniSeriesDto {
    /**
     * 
     * @type {number}
     * @memberof MiniSeriesDto
     */
    losses: number;
    /**
     * 
     * @type {string}
     * @memberof MiniSeriesDto
     */
    progress: string;
    /**
     * 
     * @type {number}
     * @memberof MiniSeriesDto
     */
    target: number;
    /**
     * 
     * @type {number}
     * @memberof MiniSeriesDto
     */
    wins: number;
}

/**
 * Check if a given object implements the MiniSeriesDto interface.
 */
export function instanceOfMiniSeriesDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "losses" in value;
    isInstance = isInstance && "progress" in value;
    isInstance = isInstance && "target" in value;
    isInstance = isInstance && "wins" in value;

    return isInstance;
}

export function MiniSeriesDtoFromJSON(json: any): MiniSeriesDto {
    return MiniSeriesDtoFromJSONTyped(json, false);
}

export function MiniSeriesDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MiniSeriesDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'losses': json['losses'],
        'progress': json['progress'],
        'target': json['target'],
        'wins': json['wins'],
    };
}

export function MiniSeriesDtoToJSON(value?: MiniSeriesDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'losses': value.losses,
        'progress': value.progress,
        'target': value.target,
        'wins': value.wins,
    };
}

