/* tslint:disable */
/* eslint-disable */
/**
 * POTG
 * POTG RestAPI Document
 *
 * The version of the OpenAPI document: BETA1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Observer
 */
export interface Observer {
    /**
     * 
     * @type {string}
     * @memberof Observer
     */
    encryptionKey: string;
}

/**
 * Check if a given object implements the Observer interface.
 */
export function instanceOfObserver(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "encryptionKey" in value;

    return isInstance;
}

export function ObserverFromJSON(json: any): Observer {
    return ObserverFromJSONTyped(json, false);
}

export function ObserverFromJSONTyped(json: any, ignoreDiscriminator: boolean): Observer {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'encryptionKey': json['encryptionKey'],
    };
}

export function ObserverToJSON(value?: Observer | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'encryptionKey': value.encryptionKey,
    };
}

