/* tslint:disable */
/* eslint-disable */
/**
 * POTG
 * POTG RestAPI Document
 *
 * The version of the OpenAPI document: BETA1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Summoner
 */
export interface Summoner {
    /**
     * 
     * @type {string}
     * @memberof Summoner
     */
    accountId: string;
    /**
     * 
     * @type {number}
     * @memberof Summoner
     */
    profileIconId: number;
    /**
     * 
     * @type {number}
     * @memberof Summoner
     */
    revisionDate: number;
    /**
     * 
     * @type {string}
     * @memberof Summoner
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Summoner
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Summoner
     */
    puuid: string;
    /**
     * 
     * @type {number}
     * @memberof Summoner
     */
    summonerLevel: number;
}

/**
 * Check if a given object implements the Summoner interface.
 */
export function instanceOfSummoner(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "accountId" in value;
    isInstance = isInstance && "profileIconId" in value;
    isInstance = isInstance && "revisionDate" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "puuid" in value;
    isInstance = isInstance && "summonerLevel" in value;

    return isInstance;
}

export function SummonerFromJSON(json: any): Summoner {
    return SummonerFromJSONTyped(json, false);
}

export function SummonerFromJSONTyped(json: any, ignoreDiscriminator: boolean): Summoner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accountId': json['accountId'],
        'profileIconId': json['profileIconId'],
        'revisionDate': json['revisionDate'],
        'name': json['name'],
        'id': json['id'],
        'puuid': json['puuid'],
        'summonerLevel': json['summonerLevel'],
    };
}

export function SummonerToJSON(value?: Summoner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'accountId': value.accountId,
        'profileIconId': value.profileIconId,
        'revisionDate': value.revisionDate,
        'name': value.name,
        'id': value.id,
        'puuid': value.puuid,
        'summonerLevel': value.summonerLevel,
    };
}

